name: Plugin PR CI

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - "plugin/market-sync/**"
      - ".github/workflows/plugin-*.yml"
      - ".github/actions/setup-authme-lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup AuthMe compile dependency
        uses: ./.github/actions/setup-authme-lib

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./plugin/market-sync
        run: mvn -B test --file pom.xml
